#Обрабатывает поисковые запросы с автокомплита
app_catalog_suggest:
    path: /suggest/
    defaults: { _controller: AppMainBundle:Catalog:suggest }

app_catalog_suggest_only_categories:
    path: /suggest-admin/
    defaults: { _controller: AppMainBundle:Catalog:suggestAdmin }

app_catalog_search:
    path: /search/
    defaults: { _controller: AppMainBundle:Catalog:searchResults }

app_catalog_search_results:
    path: /search-results/
    defaults: { _controller: AppMainBundle:Catalog:searchResults }

app_catalog_basket:
    path: /basket/
    defaults: { _controller: AppMainBundle:Cart:index }

app_catalog_order:
    path: /order/
    defaults: { _controller: AppMainBundle:Cart:order }

app_catalog_order_thanks:
    path: /order-thanks/
    defaults: { _controller: AppMainBundle:Cart:orderThanks }

app_main:
    resource: "@AppMainBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppAdminBundle/Controller/"
    prefix:   /admin
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_order_drawing:
    path: /order-drawing/
    defaults: { _controller: AppMainBundle:Drawing:order }

app_order_drawing_thanks:
    path: /order-drawing-thanks/
    defaults: { _controller: AppMainBundle:Drawing:thanks }