#app_catalog_sandbox:
#    pattern: /sandbox/
#    defaults: { _controller: AppCatalogBundle:Default:sandbox }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_admin_tree:
    pattern:  /admin/tree
    defaults: { _controller: AppCatalogBundle:Admin:tree }

app_catalog:
    resource: "@AppCatalogBundle/Resources/config/routing.yml"
    prefix:   /catalog/

app_trademark:
    pattern: /trademark/{alias}/
    defaults: { _controller: AppCatalogBundle:Trademark:showIndex }

app_service:
    resource: "@AppServiceBundle/Resources/config/routing.yml"
    prefix:   /service/

app_main:
    resource: "@AppMainBundle/Resources/config/routing.yml"
    prefix:   /
