#Обрабатывает поисковые запросы с автокомплита
app_catalog_suggest:
    path: /suggest/
    defaults: { _controller: AppMainBundle:Catalog:suggest }

app_catalog_search:
    path: /search/
    defaults: { _controller: AppMainBundle:Catalog:searchResults }

app_catalog_search_results:
    path: /search-results/
    defaults: { _controller: AppMainBundle:Catalog:searchResults }

app_catalog_basket:
    path: /basket/
    defaults: { _controller: AppMainBundle:Cart:index }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /adminka

sonata_admin_edit_products:
    path:  /adminka/editproducts
    defaults: { _controller: AppMainBundle:Admin:editProducts }

#TODO: Сомнительный код. Попробуй удалить и потестить. Исследуй доки SonataAdmin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /adminka

app_catalog_order:
    path: /order/
    defaults: { _controller: AppMainBundle:Cart:order }

app_catalog_order_thanks:
    path: /order_thanks/
    defaults: { _controller: AppMainBundle:Cart:orderThanks }

app_main:
    resource: "@AppMainBundle/Resources/config/routing.yml"
    prefix:   /