services:
    sonata.admin.category:
        class: App\CatalogBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: каталог, label: "Категории" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Category
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]

    sonata.admin.product:
        class: App\CatalogBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: каталог, label: "Изделия" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Product
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]

