services:
    sonata.admin.products:
        class: App\CatalogBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catalog, label: "Product" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Product
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]
    sonata.admin.categories:
        class: App\CatalogBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catalog, label: "Category" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Category
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]
    sonata.admin.trademarks:
        class: App\CatalogBundle\Admin\TrademarkAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catalog, label: "Trademark" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Trademark
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]
    sonata.admin.Devices:
        class: App\CatalogBundle\Admin\DeviceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catalog, label: "Device" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Device
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]
    sonata.admin.DeviceTypes:
        class: App\CatalogBundle\Admin\DeviceTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catalog, label: "DeviceType" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\DeviceType
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]
    sonata.admin.Series:
        class: App\CatalogBundle\Admin\SeriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catalog, label: "Series" }
        arguments:
            - ~
            - App\CatalogBundle\Entity\Series
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppCatalogBundle]]