app_catalog_explore_category:
    pattern: /{catUrl}/
    defaults: { _controller: AppCatalogBundle:Catalog:exploreRoute }

app_catalog_homepage:
    pattern:  /
    defaults: { _controller: AppCatalogBundle:Catalog:index }
