app_catalog_explore_category:
    pattern: /{catUrl}/
    defaults: { _controller: AppCatalogBundle:Catalog:exploreRoute, section: 0, gbi: 0 }

app_catalog_homepage:
    pattern:  /
    defaults: { _controller: AppCatalogBundle:Catalog:index }
