app_catalog_cart_add:
    pattern: /cart/add/
    defaults: { _controller: AppCatalogBundle:Cart:add, identity: 0, qiantity: 0 }

app_catalog_cart_remove:
    pattern: /cart/remove/
    defaults: { _controller: AppCatalogBundle:Cart:remove, identity: 0, qiantity: 0  }

app_catalog_cart_clean:
    pattern: /cart/clean/
    defaults: { _controller: AppCatalogBundle:Cart:clean }

app_catalog_explore_category:
    pattern: /{catUrl}/
    defaults: { _controller: AppCatalogBundle:Catalog:exploreRoute }
    # в этом роуте есть еще section и gbi, но если написать например section: 0,
    # то такой url не получится генерировать роутером

app_catalog_homepage:
    pattern:  /
    defaults: { _controller: AppCatalogBundle:Catalog:index }
