app_catalog_cart_add:
    pattern: /cart/add/
    defaults: { _controller: AppCatalogBundle:Cart:add }

app_catalog_cart_remove:
    pattern: /cart/remove/
    defaults: { _controller: AppCatalogBundle:Cart:remove }

app_catalog_cart_clean:
    pattern: /cart/clean/
    defaults: { _controller: AppCatalogBundle:Cart:clean }

app_catalog_categories:
    pattern: /categories/
    defaults: { _controller: AppCatalogBundle:Catalog:categoriesFull }

app_catalog_category:
    pattern: /categories/{id}/
    defaults: { _controller: AppCatalogBundle:Catalog:category }

app_catalog_product:
    pattern: /products/{id}/
    defaults: { _controller: AppCatalogBundle:Catalog:product }

app_catalog_gbi_visual:
    pattern: /visual/
    defaults: { _controller: AppCatalogBundle:Catalog:gbiVisual }

# TODO: добавлено июль 2015. Снеси эти роуты и редиректы, когда их не останется в индексе.
modx_catalog_explore:
    pattern: /{chain}/{lastId}/
    defaults: { _controller: AppMainBundle:Redirect:appCatalogExplore }
    requirements:
        chain: ".+"

# TODO: добавлено июль 2015. Снеси эти роуты и редиректы, когда их не останется в индексе.
modx_catalog_explore_category:
    pattern: /{categoryTranslit}/
    defaults: { _controller: AppMainBundle:Redirect:appCatalogExploreTranslit }
    requirements:
        categoryTranslit: "prom-stroy|dor-stroy|ingener-stroy|energy-stroy|blag-territory|neftegaz-stroy"

# Старый урл с get-параметрами section и gbi
app_catalog_explore_category:
    pattern: /{catUrl}/
    defaults: { _controller: AppCatalogBundle:Catalog:exploreRoute }