app_catalog_gbi_visual:
    pattern: /visual/
    defaults: { _controller: AppCatalogBundle:Catalog:gbiVisual }

app_catalog_explore_category:
    pattern: /{catUrl}/
    defaults: { _controller: AppCatalogBundle:Catalog:exploreRoute }
    # в этом роуте есть еще section и gbi, но если написать например section: 0,
    # то такой url не получится генерировать роутером

app_catalog_homepage:
    pattern:  /
    defaults: { _controller: AppCatalogBundle:Catalog:index }