parameters:
#    app_catalog.example.class: App\CatalogBundle\Example

services:
#    app_catalog.example:
#        class: %app_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
