parameters:
#    app_catalog.example.class: App\CatalogBundle\Example

services:
    catalog.search:
        class: App\CatalogBundle\Extension\Search
        arguments: ['@service_container']
    catalog.cart:
        class: App\CatalogBundle\Extension\CartService
        arguments: ['@service_container']        
    app.twig_extension:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
    app.tree_extension:
        class: App\CatalogBundle\Extension\CategoryTreeExtension
        arguments:
            entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }
    catalog.yandex_market_category_listener:
        class: App\CatalogBundle\Listener\YmlCategoryListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: yandex_market.yml.listener }
    catalog.yandex_market_product_listener:
        class: App\CatalogBundle\Listener\YmlProductListener
        arguments: ['@service_container']
        tags:
            - { name: yandex_market.yml.listener }
    catalog.yandex_market_currency_listener:
        class: App\CatalogBundle\Listener\YmlCurrencyListener
        tags:
            - { name: yandex_market.yml.listener }

    sonata.block.service.tablegear:
        class: App\CatalogBundle\Block\TableGearBlockService
        arguments: [ "sonata.block.service.tablegear", @templating ]
        tags:
            - { name: sonata.block }

    catalog.sitemap.category:
        class: App\CatalogBundle\Listener\CategorySitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]

    catalog.sitemap.product:
        class: App\CatalogBundle\Listener\ProductSitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]
