parameters:
#    app_catalog.example.class: App\CatalogBundle\Example

services:
    catalog.autocomplete:
        class: App\CatalogBundle\Extension\Autocomplete
        arguments: ['@service_container']

    app.twig_extension:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
