parameters:
#    app_catalog.example.class: App\CatalogBundle\Example

services:
    catalog.autocomplete:
        class: App\CatalogBundle\Extension\Autocomplete
        arguments: ['@service_container']
    catalog.cart:
        class: App\CatalogBundle\Extension\CartService
        arguments: ['@service_container']