services:
    sonata.admin.staticPage:
        class: App\MainBundle\Admin\StaticPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: pages, label: "StaticPage" }
        arguments:
            - ~
            - App\MainBundle\Entity\StaticPage
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [AppMainBundle]]
    sonata.admin.news:
            class: App\MainBundle\Admin\NewsAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: pages, label: "News" }
            arguments:
                - ~
                - App\MainBundle\Entity\News
                - 'SonataAdminBundle:CRUD'
            calls:
                - [ setTranslationDomain, [AppMainBundle]]

