services:
    catalog.sitemap.object:
        class: App\MainBundle\Listener\ObjectSitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]

    catalog.sitemap.post:
        class: App\MainBundle\Listener\PostSitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]

    catalog.sitemap.staticpage:
        class: App\MainBundle\Listener\StaticPageSitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]

    catalog.sitemap.post:
        class: App\MainBundle\Listener\PostSitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]

    catalog.sitemap.territory:
        class: App\MainBundle\Listener\TerritorySitemapListener
        arguments: ['@service_container']
        tags: [{name: "presta.sitemap.listener"}]